### ISSUE TITLE
stack-buffer-overflow was found at ./include/fastdds/rtps/messages/CDRMessage.hpp:134:18 [9132]

### ISSUE THREAD

**Issue by luckyzfl** [eProsima/Fast-DDS#1338]
stack-buffer-overflow was found at ./include/fastdds/rtps/messages/CDRMessage.hpp:134:18

This crash is similar to issue https://github.com/eProsima/Fast-DDS/issues/1337.
But the crash position was not same.

Here is the full crash information.

```
=================================================================
==694421==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fd1b6dd80c0 at pc 0x7fd1bd5e526a bp 0x7fd1b6dd8070 sp 0x7fd1b6dd8068
WRITE of size 1 at 0x7fd1b6dd80c0 thread T4
    #0 0x7fd1bd5e5269 in eprosima::fastrtps::rtps::CDRMessage::readDataReversed(eprosima::fastrtps::rtps::CDRMessage_t*, unsigned char*, unsigned int) /root/feilong/fast-dds/src/fastrtps/include/fastdds/rtps/messages/CDRMessage.hpp:134:18
    #1 0x7fd1bd5e5269 in eprosima::fastrtps::rtps::CDRMessage::readUInt32(eprosima::fastrtps::rtps::CDRMessage_t*, unsigned int*) /root/feilong/fast-dds/src/fastrtps/include/fastdds/rtps/messages/CDRMessage.hpp:183
    #2 0x7fd1bd5e5269 in eprosima::fastrtps::rtps::CDRMessage::readSequenceNumberSet(eprosima::fastrtps::rtps::CDRMessage_t*) /root/feilong/fast-dds/src/fastrtps/include/fastdds/rtps/messages/CDRMessage.hpp:242
    #3 0x7fd1bd5d4a4b in eprosima::fastrtps::rtps::MessageReceiver::proc_Submsg_Gap(eprosima::fastrtps::rtps::CDRMessage_t*, eprosima::fastrtps::rtps::SubmessageHeader_t*) /root/feilong/fast-dds/src/fastrtps/src/cpp/rtps/messages/MessageReceiver.cpp:968:35
    #4 0x7fd1bd5b3e69 in eprosima::fastrtps::rtps::MessageReceiver::processCDRMsg(eprosima::fastrtps::rtps::Locator_t const&, eprosima::fastrtps::rtps::CDRMessage_t*) /root/feilong/fast-dds/src/fastrtps/src/cpp/rtps/messages/MessageReceiver.cpp:273:29
    #5 0x7fd1bd5f2334 in eprosima::fastrtps::rtps::ReceiverResource::OnDataReceived(unsigned char const*, unsigned int, eprosima::fastrtps::rtps::Locator_t const&, eprosima::fastrtps::rtps::Locator_t const&) /root/feilong/fast-dds/src/fastrtps/src/cpp/rtps/network/ReceiverResource.cpp:105:14
    #6 0x7fd1bd8dae8a in eprosima::fastdds::rtps::UDPChannelResource::perform_listen_operation(eprosima::fastrtps::rtps::Locator_t) /root/feilong/fast-dds/src/fastrtps/src/cpp/rtps/transport/UDPChannelResource.cpp:66:33
    #7 0x7fd1bd8e3feb in void std::_Mem_fn_base<void (eprosima::fastdds::rtps::UDPChannelResource::*)(eprosima::fastrtps::rtps::Locator_t), true>::operator()<eprosima::fastrtps::rtps::Locator_t, void>(eprosima::fastdds::rtps::UDPChannelResource*, eprosima::fastrtps::rtps::Locator_t&&) const /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/functional:600:11
    #8 0x7fd1bd8e3feb in void std::_Bind_simple<std::_Mem_fn<void (eprosima::fastdds::rtps::UDPChannelResource::*)(eprosima::fastrtps::rtps::Locator_t)> (eprosima::fastdds::rtps::UDPChannelResource*, eprosima::fastrtps::rtps::Locator_t)>::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/functional:1530
    #9 0x7fd1bd8e3feb in std::_Bind_simple<std::_Mem_fn<void (eprosima::fastdds::rtps::UDPChannelResource::*)(eprosima::fastrtps::rtps::Locator_t)> (eprosima::fastdds::rtps::UDPChannelResource*, eprosima::fastrtps::rtps::Locator_t)>::operator()() /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/functional:1520
    #10 0x7fd1bd8e3feb in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (eprosima::fastdds::rtps::UDPChannelResource::*)(eprosima::fastrtps::rtps::Locator_t)> (eprosima::fastdds::rtps::UDPChannelResource*, eprosima::fastrtps::rtps::Locator_t)> >::_M_run() /usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/thread:115
    #11 0x7fd1bb967e5d  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd0e5d)
    #12 0x7fd1bc9436b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #13 0x7fd1bb0b34dc in clone /build/glibc-e6zv40/glibc-2.23/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Address 0x7fd1b6dd80c0 is located in stack of thread T4 at offset 64 in frame
    #0 0x7fd1bd5e3bbf in eprosima::fastrtps::rtps::CDRMessage::readSequenceNumberSet(eprosima::fastrtps::rtps::CDRMessage_t*) /root/feilong/fast-dds/src/fastrtps/include/fastdds/rtps/messages/CDRMessage.hpp:230

  This frame has 1 object(s):
    [32, 64) 'bitmap' (line 239) <== Memory access at offset 64 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
Thread T4 created by T0 here:
    #0 0x44bb2d in pthread_create /root/CL/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:317
    #1 0x7fd1bb967f63 in std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd0f63)

SUMMARY: AddressSanitizer: stack-buffer-overflow /root/feilong/fast-dds/src/fastrtps/include/fastdds/rtps/messages/CDRMessage.hpp:134:18 in eprosima::fastrtps::rtps::CDRMessage::readDataReversed(eprosima::fastrtps::rtps::CDRMessage_t*, unsigned char*, unsigned int)
Shadow bytes around the buggy address:
  0x0ffab6db2fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffab6db2fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffab6db2fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffab6db2ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffab6db3000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ffab6db3010: f1 f1 f1 f1 00 00 00 00[f3]f3 f3 f3 00 00 00 00
  0x0ffab6db3020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffab6db3030: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
  0x0ffab6db3040: 00 00 f2 f2 00 f2 f2 f2 00 00 00 00 00 00 04 f3
  0x0ffab6db3050: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffab6db3060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==694421==ABORTING

```

And the code where the crash appeared:
```C
134    *(o + i) = *(msg->buffer + msg->pos + length - 1 - i);
```

## Expected Behavior

The program should not broken down during the fuzzing process.

## Current Behavior

The program broke down and AddressSanitizer printed the error information. 

## Steps to Reproduce

1.
2.
3.
4.

## System information

- Fast-RTPS version:  commit 61e907e7ab14cb5a683ba3d3be2906913a335e8b
- OS:  Ubuntu 16.04
- Network interfaces: 
                      
- ROS2: 
        

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by EduPonz** [comment]
Hi @luckyzfl ,

Thanks for your report. We'll allocate resource to this issue as soon as we have them available.
