### ISSUE TITLE
'No space left on device' when using FASTDDS_ENVIRONMENT_FILE environment variable

### ISSUE THREAD

**Issue by AdamGoertz** [eProsima/Fast-DDS#4778]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

Apologies if this is an old issue. I searched past github issues as well as release notes looking for a clear reference to this crash, but did not see one.

### Expected behavior

Launching a ROS 2 node should not crash when the FASTDDS_ENVIRONMENT_FILE environment variable is set.

### Current behavior

Currently, launching any ROS 2 node with the FASTDDS_ENVIRONMENT_FILE set to any existing `.json` file causes a crash with a 'No space left on device' error. When the environment variable is unset or set to a non-existent file, the crash does not occur.

Backtrace in GDB:

```bash
$ FASTDDS_ENVIRONMENT_FILE=/tmp/tmp.json gdb --args /opt/ros/humble/lib/examples_rclcpp_minimal_publisher/publisher_member_function

...

terminate called after throwing an instance of 'std::system_error'
  what():  No space left on device

Thread 1 "publisher_membe" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737344044864) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737344044864)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737344044864) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737344044864, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff78ee476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff78d47f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7b97b9e in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7ba320c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7ba3277 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7ba34d8 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff6f493f8 in ?? () from /opt/ros/humble/lib/libfastrtps.so.2.6
#10 0x00007ffff706a9a4 in eprosima::fastrtps::rtps::RTPSDomain::createParticipant(unsigned int, bool, eprosima::fastrtps::rtps::RTPSParticipantAttributes const&, eprosima::fastrtps::rtps::RTPSParticipantListener*) () from /opt/ros/humble/lib/libfastrtps.so.2.6
#11 0x00007ffff70c67b0 in eprosima::fastdds::dds::DomainParticipantImpl::enable() ()
   from /opt/ros/humble/lib/libfastrtps.so.2.6
#12 0x00007ffff70c8976 in eprosima::fastdds::dds::DomainParticipantFactory::create_participant(unsigned int, eprosima::fastdds::dds::DomainParticipantQos const&, eprosima::fastdds::dds::DomainParticipantListener*, eprosima::fastdds::dds::StatusMask const&) ()
   from /opt/ros/humble/lib/libfastrtps.so.2.6
#13 0x00007ffff75d1db3 in ?? () from /opt/ros/humble/lib/librmw_fastrtps_shared_cpp.so
#14 0x00007ffff75dde8d in rmw_fastrtps_shared_cpp::create_participant(char const*, unsigned long, rmw_security_options_s const*, bool, char const*, rmw_dds_common::Context*) ()
   from /opt/ros/humble/lib/librmw_fastrtps_shared_cpp.so
#15 0x00007ffff7630c23 in ?? () from /opt/ros/humble/lib/librmw_fastrtps_cpp.so
#16 0x00007ffff76392a0 in rmw_create_node () from /opt/ros/humble/lib/librmw_fastrtps_cpp.so
#17 0x00007ffff7d9f2ea in rcl_node_init () from /opt/ros/humble/lib/librcl.so
#18 0x00007ffff7ecca4d in rclcpp::node_interfaces::NodeBase::NodeBase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<rclcpp::Context>, rcl_node_options_s const&, bool, bool) () from /opt/ros/humble/lib/librclcpp.so
#19 0x00007ffff7ec4997 in rclcpp::Node::Node(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::NodeOptions const&) () from /opt/ros/humble/lib/librclcpp.so
#20 0x00007ffff7ec5bc8 in rclcpp::Node::Node(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::NodeOptions const&) () from /opt/ros/humble/lib/librclcpp.so
#21 0x0000555555560a32 in ?? ()
#22 0x00007ffff78d5d90 in __libc_start_call_main (main=main@entry=0x555555560920,
    argc=argc@entry=1, argv=argv@entry=0x7fffffffd948) at ../sysdeps/nptl/libc_start_call_main.h:58
#23 0x00007ffff78d5e40 in __libc_start_main_impl (main=0x555555560920, argc=1, argv=0x7fffffffd948,
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffd938)
    at ../csu/libc-start.c:392
#24 0x0000555555561805 in ?? ()
```

### Steps to reproduce

```bash
$ . /opt/ros/humble/setup.bash 
$ touch /tmp/tmp.json
$ export FASTDDS_ENVIRONMENT_FILE=/tmp/tmp.json
$ ros2 run examples_rclcpp_minimal_publisher publisher_member_function
terminate called after throwing an instance of 'std::system_error'
  what():  No space left on device
[ros2run]: Aborted
```

### Fast DDS version/commit

Using ROS2 Humble install from debian packages:

```
fastdds-tools/jammy,now 2.5.0+ds-3 amd64 [installed]
libfastcdr1/jammy,now 1.0.23-1 amd64 [installed,automatic]
libfastrtps2.5/jammy,now 2.5.0+ds-3 amd64 [installed,automatic]
ros-humble-fastcdr/jammy,now 1.0.24-2jammy.20240217.024447 amd64 [installed,automatic]
ros-humble-fastrtps-cmake-module/jammy,now 2.2.2-2jammy.20240217.035841 amd64 [installed,automatic]
ros-humble-fastrtps/jammy,now 2.6.7-1jammy.20240217.034748 amd64 [installed,automatic]
ros-humble-rmw-fastrtps-cpp/jammy,now 6.2.6-1jammy.20240217.063351 amd64 [installed,automatic]
ros-humble-rmw-fastrtps-shared-cpp/jammy,now 6.2.6-1jammy.20240217.062037 amd64 [installed,automatic]
ros-humble-rosidl-typesupport-fastrtps-c/jammy,now 2.2.2-2jammy.20240217.044528 amd64 [installed,automatic]
ros-humble-rosidl-typesupport-fastrtps-cpp/jammy,now 2.2.2-2jammy.20240217.043520 amd64 [installed,automatic]
```

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

OS: Ubuntu 22.04.4 Jammy

**Comment by JesusPoderoso** [comment]
Hi @AdamGoertz, thanks for using Fast DDS.
I run the following commands with successful results:
```bash
$ docker pull osrf/ros:humble-desktop-full
$ docker run -it --rm osrf/ros:humble-desktop-full 
root@48d82df42a3b:/# . /opt/ros/humble/setup.bash 
root@48d82df42a3b:/# touch /tmp/tmp.json
root@48d82df42a3b:/# export FASTDDS_ENVIRONMENT_FILE=/tmp/tmp.json
root@48d82df42a3b:/# ros2 run examples_rclcpp_minimal_publisher publisher_member_function
[INFO] [1715692524.849740266] [minimal_publisher]: Publishing: 'Hello, world! 0'
[INFO] [1715692525.349803890] [minimal_publisher]: Publishing: 'Hello, world! 1'
[INFO] [1715692525.850023734] [minimal_publisher]: Publishing: 'Hello, world! 2'
[INFO] [1715692526.350012585] [minimal_publisher]: Publishing: 'Hello, world! 3'
[INFO] [1715692526.850117326] [minimal_publisher]: Publishing: 'Hello, world! 4'
[INFO] [1715692527.349731265] [minimal_publisher]: Publishing: 'Hello, world! 5'
[INFO] [1715692527.849698845] [minimal_publisher]: Publishing: 'Hello, world! 6'
[INFO] [1715692528.349803063] [minimal_publisher]: Publishing: 'Hello, world! 7'
[INFO] [1715692528.849874579] [minimal_publisher]: Publishing: 'Hello, world! 8'
[INFO] [1715692529.349696467] [minimal_publisher]: Publishing: 'Hello, world! 9'
[INFO] [1715692529.849843581] [minimal_publisher]: Publishing: 'Hello, world! 10'
[INFO] [1715692530.349720073] [minimal_publisher]: Publishing: 'Hello, world! 11'
```

Have you checked the amount of free space on your computer?
Were you running any DDS applications that were creating huge memory segments?

**Comment by AdamGoertz** [comment]
Odd, I just rebooted my computer and it no longer crashes. Must have been something strange going on with my system-- I checked and I had 400GB of disk space and 25+GB of memory available. 

I'll go ahead and close this, thanks!

**Comment by AdamGoertz** [comment]
Just as one more quick followup, I actually experienced this again after re-booting. I re-booted one more time and the issue is gone again. It hasn't yet re-appeared even though I tested with the same procedure as before. Very strange; if I keep seeing this crash and figure out how to reproduce it I may reopen this issue.

**Comment by JesusPoderoso** [comment]
Perfect, thanks @AdamGoertz!
